# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Help Center"
email: info@canopyws.com
description: "Simple and flexible Canopy for help center."
baseurl: "/"
url: "https://portal.canopyws.com"
twitter_username: ""
github_username:  ""
color_theme:  "#5D6272"
color_text:  "#fff"
language:  "en"

# Build settings
markdown: kramdown
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin

theme: jekyll-theme-architect